apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: azure-kubernetes-demo-1
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azure-kubernetes-demo-1
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: azure-kubernetes-demo-web
        image: kuberdemo.azurecr.io/azure-kubernetes-demo_web:v1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        env:
        - name: REDIS
          value: "azure-kubernetes-demo-1"

---
apiVersion: v1
kind: Service
metadata:
  name: azure-kubernetes-demo-1
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azure-kubernetes-demo-1

